### ISSUE TITLE
Adding dependency causes run-time error and displays compatibility issues with latest libraries

### ISSUE THREAD

**Issue by trikhatarun** [Paroca72/sc-widgets#11]
```
Process: com.android.aqimonitor, PID: 10208
                                                                        java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzab; or its super classes (declaration of 'com.google.android.gms.common.internal.zzab' appears in /data/app/com.android.aqimonitor-2/split_lib_dependencies_apk.apk:classes43.dex)
                                                                            at com.google.firebase.provider.FirebaseInitProvider.zza(Unknown Source)
                                                                            at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                                            at android.app.ActivityThread.installProvider(ActivityThread.java:5233)
                                                                            at android.app.ActivityThread.installContentProviders(ActivityThread.java:4828)
                                                                            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4768)
                                                                            at android.app.ActivityThread.access$1600(ActivityThread.java:155)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1441)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:152)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5497)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

**Comment by Paroca72** [comment]
Hello,

You have this problem when you add the google play services??
You already tried this?
compile "com.google.android.gms:play-services-base:+"
compile 'com.google.android.gms:play-services-location:+'
compile 'com.google.android.gms:play-services-maps:+'

sc-widgets library go in run-time error? I not seen named in your reported error?

Thanks

**Comment by trikhatarun** [comment]
```
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.android.support:gridlayout-v7:25.3.1'
    compile 'com.android.support:cardview-v7:25.3.1'
    compile 'com.jakewharton:butterknife:8.5.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.5.1'
    compile 'com.squareup.retrofit2:retrofit:2.2.0'
    compile 'com.squareup.retrofit2:converter-gson:2.2.0'
    compile 'com.google.android.gms:play-services-location:10.2.6'
    compile 'com.android.support:recyclerview-v7:25.3.1'
    testCompile 'junit:junit:4.12'
```
Above are my initial dependencies where app works great. But when I add:

```
    compile 'com.github.paroca72:sc-widgets:2.1.6'
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.android.support:gridlayout-v7:25.3.1'
    compile 'com.android.support:cardview-v7:25.3.1'
    compile 'com.jakewharton:butterknife:8.5.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.5.1'
    compile 'com.squareup.retrofit2:retrofit:2.2.0'
    compile 'com.squareup.retrofit2:converter-gson:2.2.0'
    compile 'com.google.android.gms:play-services-location:10.2.6'
    compile 'com.android.support:recyclerview-v7:25.3.1'
    testCompile 'junit:junit:4.12'
```
appcompat and play-services-location dependencies show errors:

> All support libraries must use same versions 
> All gms libraries must use same versions 

respectively.

Which is probably as I am using newer libraries but app can be run without resolving this error and when I run the app it now throws the error log mentioned initially.

I really love your library and it is best suited for the work I am doing.

**Comment by Paroca72** [comment]
Hello,

Let me a while and when I'm back home I will try to understand this issue..

Thanks
Sam

**Comment by Paroca72** [comment]
Hello,

Please try to download the new version 2.2.0 and let me know if this solve your issue..

Thanks
Sam

**Comment by trikhatarun** [comment]
Hello Sam,

Thanks for your quick response. The above solution works great.
Once again thanks for creating such an amazing library.

Regards,
Tarun
